### ISSUE TITLE
Public domain license alternatives

### ISSUE THREAD

**Issue by jakepetroules** [potionfactory/LetsMove#27]
Could this library perhaps be released under the CC0 or MIT or similar license? IIRC with just a plain 'public domain' notice this may limit this library's use in projects developed or distributed in certain jurisdictions.

**Comment by ajorg-aws** [comment]
Hello! We also find the bare words "Public Domain" to be less comforting than a thorough public domain declaration like CC0. The effect of CC0 is the same as the simple notice, but with legal *teeth*. I wonder if you'd reconsider, as for many companies the bare "Public Domain" notice is a legal speedbump.

Two other palatable licenses that are very nearly public domain are [0BSD](https://spdx.org/licenses/0BSD.html), [MIT-0](https://spdx.org/licenses/MIT-0.html), and [Unlicense](https://unlicense.org/) but it sounds like [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) fits your intentions more closely.
