### ISSUE TITLE
Doesn't work with sandboxed apps

### ISSUE THREAD

**Issue by kolpanic** [potionfactory/LetsMove#41]
I tried using LetsMove in my sandboxed app, and I kept getting `errAuthorizationDenied` when requesting the authorization to do the move. It turns out that according to [Apple's Sandbox Design guide](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/DesigningYourSandbox/DesigningYourSandbox.html#//apple_ref/doc/uid/TP40011183-CH4-SW6), sandboxed apps can't use Authorization Services. 

A note at the top of README.md could save people some time.

(Alternately, you could [detect if the app is sandboxed](http://stackoverflow.com/questions/12177948/how-do-i-detect-if-my-app-is-sandboxed), and show an alert advising the user to quit and move the app manually.)

**Comment by andypotion** [comment]
A note was added to the README. Sorry that it didn't mention it sooner.

**Comment by kolpanic** [comment]
:+1:
