### ISSUE TITLE
The main window also appears?

### ISSUE THREAD

**Issue by trudger123** [potionfactory/LetsMove#53]
Your sample project seems working fine. But when I create a new project and add your components. The main window will appear along with your window. I'm using the latest version of xcode and OS X. Could you please tell me that what I should I do? Thanks.

**Comment by andypotion** [comment]
The window must be getting opened before the call to `PFMoveToApplicationsFolderIfNecessary`.

Make sure that you are calling `PFMoveToApplicationsFolderIfNecessary` at the top of the app delegate's `-[applicationWillFinishLaunching:]` method.

If you're already doing that, then find out where the main window is getting opened by setting breakpoints on methods such as `[NSWindow orderFront:]` then call `PFMoveToApplicationsFolderIfNecessary` before the window opens.

**Comment by trudger123** [comment]
Thanks for your response. It turns out that I should disable "visible at launch" option. Now it works well.
