### ISSUE TITLE
LetsMove crashes my app on High Sierra when trying to trash it

### ISSUE THREAD

**Issue by cstigler** [potionfactory/LetsMove#64]
Hello! Hoping somebody might have an idea about why LetsMove is crashing in my open-source Mac app SelfControl on the High Sierra public beta (just tried to add it last week).

The behavior I’m seeing:

1. Open SelfControl from the Downloads folder.
2. Prompt appears, click to move it to the Applications folder.
3. SelfControl appears to be moved correctly to the Applications folder, but is not restarted.
4. Open SelfControl again from the Applications folder.
5. Prompt appears again asking to move it to the Applications folder.
6. Click to move it to the Applications folder again.
7. SelfControl quits and is trashed away from the Applications folder.

I didn’t do anything special with the integration - just the one-line call. You can see the full diff (+6 lines) of the installation [here](https://github.com/SelfControlApp/selfcontrol/compare/lets-move).

I determined that the issue is the AppleScript that gets run on [line 390 of PFMoveApplication.m](https://github.com/potionfactory/LetsMove/blob/master/PFMoveApplication.m#L390) to trash the app. On the LetsMove sample app, it runs successfully. But in SelfControl, despite having basically identical parameters (the app is in the `/AppTranslocation/` folder in both cases), running that AppleScript crashes the app and it never gets further. I also see an error logged in the console that isn’t logged for LetsMove: `        OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(spec,phac handler=0x7fff8fde98ee isSys=YES) err=0/noErr`

Any ideas what this could be? I’ll keep trying to debug but I’m not sure where to go from here.

**Comment by cstigler** [comment]
OK, I actually found the issue just after posting this... my app returns `YES` on the `applicationShouldTerminateAfterLastWindowClosed` method of `NSApplicationDelegate`. If I return `NO` instead, it works fine. I believe that the app is terminating (and therefore the translocated file is disappearing) before the AppleScript has a chance to run. I'll think a bit about possibilities to solve this and submit a PR if I think the fix should be in LetsMove.

**Comment by cstigler** [comment]
Pull request to allow working around this issue: https://github.com/potionfactory/LetsMove/pull/65

**Comment by jwatt** [comment]
@cstigler I guess you can close this now since your PR got merged?

**Comment by cstigler** [comment]
@jwatt yep good point, it's been resolved for a long while now!
