### ISSUE TITLE
Unknown type name 'BOOL'

### ISSUE THREAD

**Issue by aonez** [potionfactory/LetsMove#71]
https://github.com/potionfactory/LetsMove/blob/c04de83b496896698515e27e377ccc249662f808/PFMoveApplication.h#L26

Moving this import to the `.h` file solves the issue.

https://github.com/potionfactory/LetsMove/blob/c04de83b496896698515e27e377ccc249662f808/PFMoveApplication.m#L12

**Comment by jwatt** [comment]
@aonez Can you close this issue? That import is now in the .h file.
